//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BorrowLendParams {
pub borrows_limit_in_bps: u64,
pub maintainance_margin_bps: u64,
pub protocol_fee_bps: u64,
pub liquidation_margin: u64,
pub liquidation_fee_bps: u64,
}


