//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::RequestType;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateDecreasePositionRequest2Params {
pub collateral_usd_delta: u64,
pub size_usd_delta: u64,
pub request_type: RequestType,
pub price_slippage: Option<u64>,
pub jupiter_minimum_out: Option<u64>,
pub trigger_price: Option<u64>,
pub trigger_above_threshold: Option<bool>,
pub entire_position: Option<bool>,
pub counter: u64,
}


