//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::PricingParams;
use crate::generated::types::JumpRateState;
use crate::generated::types::BorrowLendParams;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct OperatorSetCustodyConfigParams {
pub pricing: PricingParams,
pub hourly_funding_dbps: u64,
pub target_ratio_bps: u64,
pub increase_position_bps: u64,
pub decrease_position_bps: u64,
pub max_position_size_usd: u64,
pub jump_rate: JumpRateState,
pub price_impact_fee_factor: u64,
pub price_impact_exponent: f32,
pub delta_imbalance_threshold_decimal: u64,
pub max_fee_bps: u64,
pub borrow_lend_parameters: BorrowLendParams,
pub borrow_hourly_funding_dbps: u64,
pub borrow_limit_in_token_amount: u64,
pub min_interest_fee_bps: u64,
pub min_interest_fee_grace_period_seconds: u64,
}


