//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::Fees;
use crate::generated::types::Limit;
use crate::generated::types::Secp256k1Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetPoolConfigParams {
pub fees: Fees,
pub limit: Limit,
pub max_request_execution_sec: i64,
pub parameter_update_oracle: Secp256k1Pubkey,
}


