//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetMaxGlobalSizesParams {
pub max_global_long_size: u64,
pub max_global_short_size: u64,
pub recovery_id: u8,
#[cfg_attr(feature = "serde", serde(with = "serde_big_array::BigArray"))]
pub signature: [u8; 64],
pub reference_id: [u8; 16],
pub timestamp: u64,
}


