//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CLOSE_POSITION_REQUEST2_DISCRIMINATOR: [u8; 8] = [121, 68, 162, 28, 216, 47, 200, 66];

/// Accounts.
#[derive(Debug)]
pub struct ClosePositionRequest2 {
      
              
          pub keeper: Option<solana_pubkey::Pubkey>,
          
              
          pub owner: solana_pubkey::Pubkey,
          
              
          pub owner_ata: solana_pubkey::Pubkey,
          
              
          pub pool: solana_pubkey::Pubkey,
          
              
          pub position_request: solana_pubkey::Pubkey,
          
              
          pub position_request_ata: solana_pubkey::Pubkey,
          
              
          pub position: solana_pubkey::Pubkey,
          
              
          pub mint: solana_pubkey::Pubkey,
          
              
          pub token_program: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
          
              
          pub associated_token_program: solana_pubkey::Pubkey,
          
              
          pub event_authority: solana_pubkey::Pubkey,
          
              
          pub program: solana_pubkey::Pubkey,
      }

impl ClosePositionRequest2 {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(13+ remaining_accounts.len());
                                        if let Some(keeper) = self.keeper {
              accounts.push(solana_instruction::AccountMeta::new(
                keeper,
                true,
              ));
            } else {
              accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::PERPETUALS_ID,
                false,
              ));
            }
                                                    accounts.push(solana_instruction::AccountMeta::new(
            self.owner,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.owner_ata,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.position_request,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.position_request_ata,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.position,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = borsh::to_vec(&ClosePositionRequest2InstructionData::new()).unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::PERPETUALS_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ClosePositionRequest2InstructionData {
            discriminator: [u8; 8],
      }

impl ClosePositionRequest2InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [121, 68, 162, 28, 216, 47, 200, 66],
                  }
  }
}

impl Default for ClosePositionRequest2InstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `ClosePositionRequest2`.
///
/// ### Accounts:
///
                            ///   0. `[writable, signer, optional]` keeper
                ///   1. `[writable]` owner
                ///   2. `[writable]` owner_ata
                ///   3. `[writable]` pool
                ///   4. `[writable]` position_request
                ///   5. `[writable]` position_request_ata
          ///   6. `[]` position
          ///   7. `[]` mint
          ///   8. `[]` token_program
          ///   9. `[]` system_program
          ///   10. `[]` associated_token_program
          ///   11. `[]` event_authority
          ///   12. `[]` program
#[derive(Clone, Debug, Default)]
pub struct ClosePositionRequest2Builder {
            keeper: Option<solana_pubkey::Pubkey>,
                owner: Option<solana_pubkey::Pubkey>,
                owner_ata: Option<solana_pubkey::Pubkey>,
                pool: Option<solana_pubkey::Pubkey>,
                position_request: Option<solana_pubkey::Pubkey>,
                position_request_ata: Option<solana_pubkey::Pubkey>,
                position: Option<solana_pubkey::Pubkey>,
                mint: Option<solana_pubkey::Pubkey>,
                token_program: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                associated_token_program: Option<solana_pubkey::Pubkey>,
                event_authority: Option<solana_pubkey::Pubkey>,
                program: Option<solana_pubkey::Pubkey>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClosePositionRequest2Builder {
  pub fn new() -> Self {
    Self::default()
  }
            /// `[optional account]`
#[inline(always)]
    pub fn keeper(&mut self, keeper: Option<solana_pubkey::Pubkey>) -> &mut Self {
                        self.keeper = keeper;
                    self
    }
            #[inline(always)]
    pub fn owner(&mut self, owner: solana_pubkey::Pubkey) -> &mut Self {
                        self.owner = Some(owner);
                    self
    }
            #[inline(always)]
    pub fn owner_ata(&mut self, owner_ata: solana_pubkey::Pubkey) -> &mut Self {
                        self.owner_ata = Some(owner_ata);
                    self
    }
            #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.pool = Some(pool);
                    self
    }
            #[inline(always)]
    pub fn position_request(&mut self, position_request: solana_pubkey::Pubkey) -> &mut Self {
                        self.position_request = Some(position_request);
                    self
    }
            #[inline(always)]
    pub fn position_request_ata(&mut self, position_request_ata: solana_pubkey::Pubkey) -> &mut Self {
                        self.position_request_ata = Some(position_request_ata);
                    self
    }
            #[inline(always)]
    pub fn position(&mut self, position: solana_pubkey::Pubkey) -> &mut Self {
                        self.position = Some(position);
                    self
    }
            #[inline(always)]
    pub fn mint(&mut self, mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.mint = Some(mint);
                    self
    }
            #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
            #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            #[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.associated_token_program = Some(associated_token_program);
                    self
    }
            #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.event_authority = Some(event_authority);
                    self
    }
            #[inline(always)]
    pub fn program(&mut self, program: solana_pubkey::Pubkey) -> &mut Self {
                        self.program = Some(program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = ClosePositionRequest2 {
                              keeper: self.keeper,
                                        owner: self.owner.expect("owner is not set"),
                                        owner_ata: self.owner_ata.expect("owner_ata is not set"),
                                        pool: self.pool.expect("pool is not set"),
                                        position_request: self.position_request.expect("position_request is not set"),
                                        position_request_ata: self.position_request_ata.expect("position_request_ata is not set"),
                                        position: self.position.expect("position is not set"),
                                        mint: self.mint.expect("mint is not set"),
                                        token_program: self.token_program.expect("token_program is not set"),
                                        system_program: self.system_program.expect("system_program is not set"),
                                        associated_token_program: self.associated_token_program.expect("associated_token_program is not set"),
                                        event_authority: self.event_authority.expect("event_authority is not set"),
                                        program: self.program.expect("program is not set"),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `close_position_request2` CPI accounts.
  pub struct ClosePositionRequest2CpiAccounts<'a, 'b> {
          
                    
              pub keeper: Option<&'b solana_account_info::AccountInfo<'a>>,
                
                    
              pub owner: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub owner_ata: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub pool: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub position_request: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub position_request_ata: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub position: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub mint: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub event_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `close_position_request2` CPI instruction.
pub struct ClosePositionRequest2Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub keeper: Option<&'b solana_account_info::AccountInfo<'a>>,
          
              
          pub owner: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub owner_ata: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub pool: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub position_request: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub position_request_ata: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub position: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub mint: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub event_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub program: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> ClosePositionRequest2Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: ClosePositionRequest2CpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              keeper: accounts.keeper,
              owner: accounts.owner,
              owner_ata: accounts.owner_ata,
              pool: accounts.pool,
              position_request: accounts.position_request,
              position_request_ata: accounts.position_request_ata,
              position: accounts.position,
              mint: accounts.mint,
              token_program: accounts.token_program,
              system_program: accounts.system_program,
              associated_token_program: accounts.associated_token_program,
              event_authority: accounts.event_authority,
              program: accounts.program,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(13+ remaining_accounts.len());
                            if let Some(keeper) = self.keeper {
            accounts.push(solana_instruction::AccountMeta::new(
              *keeper.key,
              true,
            ));
          } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
              crate::PERPETUALS_ID,
              false,
            ));
          }
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.owner.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.owner_ata.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.position_request.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.position_request_ata.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.position.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = borsh::to_vec(&ClosePositionRequest2InstructionData::new()).unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::PERPETUALS_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(14 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  if let Some(keeper) = self.keeper {
          account_infos.push(keeper.clone());
        }
                        account_infos.push(self.owner.clone());
                        account_infos.push(self.owner_ata.clone());
                        account_infos.push(self.pool.clone());
                        account_infos.push(self.position_request.clone());
                        account_infos.push(self.position_request_ata.clone());
                        account_infos.push(self.position.clone());
                        account_infos.push(self.mint.clone());
                        account_infos.push(self.token_program.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.associated_token_program.clone());
                        account_infos.push(self.event_authority.clone());
                        account_infos.push(self.program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `ClosePositionRequest2` via CPI.
///
/// ### Accounts:
///
                            ///   0. `[writable, signer, optional]` keeper
                ///   1. `[writable]` owner
                ///   2. `[writable]` owner_ata
                ///   3. `[writable]` pool
                ///   4. `[writable]` position_request
                ///   5. `[writable]` position_request_ata
          ///   6. `[]` position
          ///   7. `[]` mint
          ///   8. `[]` token_program
          ///   9. `[]` system_program
          ///   10. `[]` associated_token_program
          ///   11. `[]` event_authority
          ///   12. `[]` program
#[derive(Clone, Debug)]
pub struct ClosePositionRequest2CpiBuilder<'a, 'b> {
  instruction: Box<ClosePositionRequest2CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClosePositionRequest2CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(ClosePositionRequest2CpiBuilderInstruction {
      __program: program,
              keeper: None,
              owner: None,
              owner_ata: None,
              pool: None,
              position_request: None,
              position_request_ata: None,
              position: None,
              mint: None,
              token_program: None,
              system_program: None,
              associated_token_program: None,
              event_authority: None,
              program: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      /// `[optional account]`
#[inline(always)]
    pub fn keeper(&mut self, keeper: Option<&'b solana_account_info::AccountInfo<'a>>) -> &mut Self {
                        self.instruction.keeper = keeper;
                    self
    }
      #[inline(always)]
    pub fn owner(&mut self, owner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.owner = Some(owner);
                    self
    }
      #[inline(always)]
    pub fn owner_ata(&mut self, owner_ata: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.owner_ata = Some(owner_ata);
                    self
    }
      #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.pool = Some(pool);
                    self
    }
      #[inline(always)]
    pub fn position_request(&mut self, position_request: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.position_request = Some(position_request);
                    self
    }
      #[inline(always)]
    pub fn position_request_ata(&mut self, position_request_ata: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.position_request_ata = Some(position_request_ata);
                    self
    }
      #[inline(always)]
    pub fn position(&mut self, position: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.position = Some(position);
                    self
    }
      #[inline(always)]
    pub fn mint(&mut self, mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.mint = Some(mint);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      #[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.associated_token_program = Some(associated_token_program);
                    self
    }
      #[inline(always)]
    pub fn event_authority(&mut self, event_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.event_authority = Some(event_authority);
                    self
    }
      #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.program = Some(program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = ClosePositionRequest2Cpi {
        __program: self.instruction.__program,
                  
          keeper: self.instruction.keeper,
                  
          owner: self.instruction.owner.expect("owner is not set"),
                  
          owner_ata: self.instruction.owner_ata.expect("owner_ata is not set"),
                  
          pool: self.instruction.pool.expect("pool is not set"),
                  
          position_request: self.instruction.position_request.expect("position_request is not set"),
                  
          position_request_ata: self.instruction.position_request_ata.expect("position_request_ata is not set"),
                  
          position: self.instruction.position.expect("position is not set"),
                  
          mint: self.instruction.mint.expect("mint is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          associated_token_program: self.instruction.associated_token_program.expect("associated_token_program is not set"),
                  
          event_authority: self.instruction.event_authority.expect("event_authority is not set"),
                  
          program: self.instruction.program.expect("program is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct ClosePositionRequest2CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            keeper: Option<&'b solana_account_info::AccountInfo<'a>>,
                owner: Option<&'b solana_account_info::AccountInfo<'a>>,
                owner_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
                pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                position_request: Option<&'b solana_account_info::AccountInfo<'a>>,
                position_request_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
                position: Option<&'b solana_account_info::AccountInfo<'a>>,
                mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                program: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

