//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::TestInitParams;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const TEST_INIT_DISCRIMINATOR: [u8; 8] = [48, 51, 92, 122, 81, 19, 112, 41];

/// Accounts.
#[derive(Debug)]
pub struct TestInit {
      
              
          pub upgrade_authority: solana_pubkey::Pubkey,
          
              
          pub admin: solana_pubkey::Pubkey,
          
              
          pub transfer_authority: solana_pubkey::Pubkey,
          
              
          pub perpetuals: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
          
              
          pub token_program: solana_pubkey::Pubkey,
      }

impl TestInit {
  pub fn instruction(&self, args: TestInitInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: TestInitInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.upgrade_authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.admin,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.transfer_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.perpetuals,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&TestInitInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::PERPETUALS_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct TestInitInstructionData {
            discriminator: [u8; 8],
            }

impl TestInitInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [48, 51, 92, 122, 81, 19, 112, 41],
                                }
  }
}

impl Default for TestInitInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct TestInitInstructionArgs {
                  pub params: TestInitParams,
      }


/// Instruction builder for `TestInit`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` upgrade_authority
          ///   1. `[]` admin
                ///   2. `[writable]` transfer_authority
                ///   3. `[writable]` perpetuals
          ///   4. `[]` system_program
          ///   5. `[]` token_program
#[derive(Clone, Debug, Default)]
pub struct TestInitBuilder {
            upgrade_authority: Option<solana_pubkey::Pubkey>,
                admin: Option<solana_pubkey::Pubkey>,
                transfer_authority: Option<solana_pubkey::Pubkey>,
                perpetuals: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                token_program: Option<solana_pubkey::Pubkey>,
                        params: Option<TestInitParams>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl TestInitBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn upgrade_authority(&mut self, upgrade_authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.upgrade_authority = Some(upgrade_authority);
                    self
    }
            #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin = Some(admin);
                    self
    }
            #[inline(always)]
    pub fn transfer_authority(&mut self, transfer_authority: solana_pubkey::Pubkey) -> &mut Self {
                        self.transfer_authority = Some(transfer_authority);
                    self
    }
            #[inline(always)]
    pub fn perpetuals(&mut self, perpetuals: solana_pubkey::Pubkey) -> &mut Self {
                        self.perpetuals = Some(perpetuals);
                    self
    }
            #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
                    #[inline(always)]
      pub fn params(&mut self, params: TestInitParams) -> &mut Self {
        self.params = Some(params);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = TestInit {
                              upgrade_authority: self.upgrade_authority.expect("upgrade_authority is not set"),
                                        admin: self.admin.expect("admin is not set"),
                                        transfer_authority: self.transfer_authority.expect("transfer_authority is not set"),
                                        perpetuals: self.perpetuals.expect("perpetuals is not set"),
                                        system_program: self.system_program.expect("system_program is not set"),
                                        token_program: self.token_program.expect("token_program is not set"),
                      };
          let args = TestInitInstructionArgs {
                                                              params: self.params.clone().expect("params is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `test_init` CPI accounts.
  pub struct TestInitCpiAccounts<'a, 'b> {
          
                    
              pub upgrade_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub admin: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub transfer_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub perpetuals: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `test_init` CPI instruction.
pub struct TestInitCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub upgrade_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub admin: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub transfer_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub perpetuals: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: TestInitInstructionArgs,
  }

impl<'a, 'b> TestInitCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: TestInitCpiAccounts<'a, 'b>,
              args: TestInitInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              upgrade_authority: accounts.upgrade_authority,
              admin: accounts.admin,
              transfer_authority: accounts.transfer_authority,
              perpetuals: accounts.perpetuals,
              system_program: accounts.system_program,
              token_program: accounts.token_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.upgrade_authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.admin.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.transfer_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.perpetuals.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&TestInitInstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::PERPETUALS_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.upgrade_authority.clone());
                        account_infos.push(self.admin.clone());
                        account_infos.push(self.transfer_authority.clone());
                        account_infos.push(self.perpetuals.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.token_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `TestInit` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` upgrade_authority
          ///   1. `[]` admin
                ///   2. `[writable]` transfer_authority
                ///   3. `[writable]` perpetuals
          ///   4. `[]` system_program
          ///   5. `[]` token_program
#[derive(Clone, Debug)]
pub struct TestInitCpiBuilder<'a, 'b> {
  instruction: Box<TestInitCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> TestInitCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(TestInitCpiBuilderInstruction {
      __program: program,
              upgrade_authority: None,
              admin: None,
              transfer_authority: None,
              perpetuals: None,
              system_program: None,
              token_program: None,
                                            params: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn upgrade_authority(&mut self, upgrade_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.upgrade_authority = Some(upgrade_authority);
                    self
    }
      #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin = Some(admin);
                    self
    }
      #[inline(always)]
    pub fn transfer_authority(&mut self, transfer_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.transfer_authority = Some(transfer_authority);
                    self
    }
      #[inline(always)]
    pub fn perpetuals(&mut self, perpetuals: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.perpetuals = Some(perpetuals);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
                    #[inline(always)]
      pub fn params(&mut self, params: TestInitParams) -> &mut Self {
        self.instruction.params = Some(params);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = TestInitInstructionArgs {
                                                              params: self.instruction.params.clone().expect("params is not set"),
                                    };
        let instruction = TestInitCpi {
        __program: self.instruction.__program,
                  
          upgrade_authority: self.instruction.upgrade_authority.expect("upgrade_authority is not set"),
                  
          admin: self.instruction.admin.expect("admin is not set"),
                  
          transfer_authority: self.instruction.transfer_authority.expect("transfer_authority is not set"),
                  
          perpetuals: self.instruction.perpetuals.expect("perpetuals is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct TestInitCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            upgrade_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                admin: Option<&'b solana_account_info::AccountInfo<'a>>,
                transfer_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                perpetuals: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        params: Option<TestInitParams>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

