//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#borrow_position;
  pub(crate) mod r#custody;
  pub(crate) mod r#perpetuals;
  pub(crate) mod r#pool;
  pub(crate) mod r#position;
  pub(crate) mod r#position_request;
  pub(crate) mod r#token_ledger;

  pub use self::r#borrow_position::*;
  pub use self::r#custody::*;
  pub use self::r#perpetuals::*;
  pub use self::r#pool::*;
  pub use self::r#position::*;
  pub use self::r#position_request::*;
  pub use self::r#token_ledger::*;

